spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost/blog?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC"
      username: developer
      password: password
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      #pool-name: pool-jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: false
    show-sql: true
server:
  port: 8000